name: Build/Deploy

on:
    workflow_dispatch:
        inputs:
            repo_name:
                description: 'Name of the Repository'
                required: true
                type: choice
                options:
                  - 'CoreLearner'
                  - 'DemoNotCore'

            environment:
                description: 'Environment to build'
                required: true
                type: choice
                options:
                  - 'INT'
                  - 'QA'

# Define environment variables that can be used in the workflow. 
env:
    REPO_NAME: ${{ github.event.inputs.repo_name }}
    REPO_URL: "https://zyousaf31@github.com/ZeeLearning/${{ github.event.inputs.repo_name }}.git"
    WORKSPACE_DIRECTORY: ${{ github.workspace }}
    PLATFORM: 'Any CPU'

jobs:
    Checkout_Target_Repo:
        runs-on: self-hosted
        environment: ${{ github.event.inputs.environment }}
        # Set the output for the solution name
        outputs:
            SOLUTION_NAME: ${{ steps.get_solution_name.outputs.solutionName }}
            SOLUTION_PATH: ${{ steps.get_solution_name.outputs.solutionPath}}
        steps:
            # Checkout the target repo
            - name: Check out the target repo 
              run: |
                git clone --branch ${{ vars.BRANCH }} ${{ env.REPO_URL}} ${{ env.REPO_NAME }}
                cd ${{ env.REPO_NAME }}
                echo "Cloned repository: ${{ env.REPO_NAME }} (branch: ${{ vars.BRANCH }})"
                git branch 
                echo ${{ env.WORKSPACE_DIRECTORY }}
            
            # Get solution file name 
            - name: Get solution file name
              id: get_solution_name
              run: |
                cd ${{ env.REPO_NAME }}
                $solution = Get-ChildItem -Path . -Filter *.sln -Recurse
                $solutionName = $solution.Name
                $solutionPath = $solution.FullName
                echo "Solution file path: $solutionPath"
                echo "Solution file name: $solutionName"
                echo "solutionName=$solutionName" >> $env:GITHUB_OUTPUT
                echo "solutionPath=$solutionPath" >> $env:GITHUB_OUTPUT

            - name: Show Solution Name Output
              run: |
                echo "Solution name set as output: ${{ steps.get_solution_name.outputs.solutionName }}"
                echo "Solution path set as output: ${{ steps.get_solution_name.outputs.solutionPath }}"

    NuGet_Restore:
        runs-on: self-hosted
        needs: [Checkout_Target_Repo]
        environment: ${{ github.event.inputs.environment }}
        steps:
            - name: Restore NuGet packages (.NET Core)
              if: ${{ github.event.inputs.repo_name == 'CoreLearner' }}
              run: |
                cd ${{ env.REPO_NAME }}
                dotnet restore
                echo "Configuration - ${{ vars.CONFIGURATION }}"

            - name: Restore NuGet packages (.NET Framework)
              if: ${{ github.event.inputs.repo_name == 'DemoNotCore' }}
              run: |
                cd ${{ env.REPO_NAME }}
                nuget restore ${{ needs.Checkout_Target_Repo.outputs.SOLUTION_NAME }}
                echo "Configuration - ${{ vars.CONFIGURATION }}"

    Build:
        runs-on: self-hosted
        needs: [Checkout_Target_Repo, NuGet_Restore]
        environment: ${{ github.event.inputs.environment }}
        steps:
            - name: Build the solution (.NET Core)
              if: ${{ github.event.inputs.repo_name == 'CoreLearner' }}
              run: |
                cd ${{ env.REPO_NAME }}
                dotnet build --configuration ${{ vars.CONFIGURATION}}
                echo "Configuration - ${{ vars.CONFIGURATION }}"

            - name: Build the solution (.NET Framework)
              if: ${{ github.event.inputs.repo_name == 'DemoNotCore' }}
              run: |
                cd ${{ env.REPO_NAME }}
                msbuild ${{ needs.Checkout_Target_Repo.outputs.SOLUTION_NAME }} /p:Configuration=${{ vars.CONFIGURATION}} /p:Platform="${{ env.PLATFORM }}"
                echo "Configuration - ${{ vars.CONFIGURATION }}"
  
    Clean_Up:
        runs-on: self-hosted
        needs: [Checkout_Target_Repo, NuGet_Restore, Build]
        steps:
            # Clean the target repo
            - name: Clean the target repo
              run: |
                cd ${{ env.WORKSPACE_DIRECTORY }}
                Remove-Item -Recurse -Force ${{ env.REPO_NAME }}
                echo "Cleaned up the target repo"# Empty workflow file 
