name: summary 

on: 
    workflow_dispatch:

jobs:
    summaries:
        runs-on: ubuntu-latest

        steps:
            - name: Show GitHub Summary
              run: |
                echo "### Summary" >> $GITHUB_STEP_SUMMARY
    